// import type { Course } from "./types";

// export const MOCK_COURSES: Course[] = [
//   { id: 1, courseName: "Advanced Data Science Bootcamp", description: "Deep dive into AI and machine learning.", keywords: ["data science", "ai", "machine learning", "python"], fees: 4500, duration: 2, institutionName: "Tech University", location: "New York", latitude: 40.7128, longitude: -74.0060, mode: "Online" },
//   { id: 2, courseName: "Python for Beginners", description: "Learn the basics of Python programming.", keywords: ["python", "coding", "beginners"], fees: 1200, duration: 1.5, institutionName: "Code Academy", location: "New York", latitude: 40.7128, longitude: -74.0060, mode: "Offline" },
//   { id: 3, courseName: "Full-Stack Web Development", description: "Become a full-stack developer with this comprehensive course.", keywords: ["web development", "javascript", "react", "full-stack"], fees: 6000, duration: 3, institutionName: "Dev Institute", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 4, courseName: "Machine Learning Engineering", description: "Master the skills needed to become a machine learning engineer.", keywords: ["machine learning", "ai", "data science"], fees: 7000, duration: 2.5, institutionName: "AI Core", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Online" },
//   { id: 5, courseName: "Introduction to Data Science", description: "Get started with data science and analytics.", keywords: ["data science", "python", "intro"], fees: 3000, duration: 1, institutionName: "City College", location: "New York", latitude: 40.7128, longitude: -74.0060, mode: "Offline" },
//   { id: 6, courseName: "UX/UI Design Fundamentals", description: "Learn the principles of UX/UI design.", keywords: ["ux", "ui", "design"], fees: 2500, duration: 1, institutionName: "Design Hub", location: "Chicago", latitude: 41.8781, longitude: -87.6298, mode: "Online" },
//   { id: 7, courseName: "Data Science Specialization", description: "Deepen your data science knowledge.", keywords: ["data science", "statistics"], fees: 2000, duration: 3, institutionName: "Online University", location: "Online", latitude: 0, longitude: 0, mode: "Online" },
//   { id: 8, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 4800, duration: 2, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 9, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 5800, duration: 2, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 10, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 6800, duration: 2, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 11, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 7800, duration: 2.5, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 12, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 8800, duration: 2.5, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 13, courseName: "Python & Data Science Program", description: "Combine Python programming with data science.", keywords: ["python", "data science"], fees: 9800, duration: 2.5, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
//   { id: 14, courseName: "Web Development", description: "Learn web development from scratch.", keywords: ["web development", "javascript", "html", "css"], fees: 9800, duration: 2.5, institutionName: "Tech Institute SF", location: "San Francisco", latitude: 37.7749, longitude: -122.4194, mode: "Hybrid" },
// ];